/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ping.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ping.pb-c.h"
void   ping__ping_req__init
                     (Ping__PingReq         *message)
{
  static const Ping__PingReq init_value = PING__PING_REQ__INIT;
  *message = init_value;
}
size_t ping__ping_req__get_packed_size
                     (const Ping__PingReq *message)
{
  assert(message->base.descriptor == &ping__ping_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ping__ping_req__pack
                     (const Ping__PingReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ping__ping_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ping__ping_req__pack_to_buffer
                     (const Ping__PingReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ping__ping_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ping__PingReq *
       ping__ping_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ping__PingReq *)
     protobuf_c_message_unpack (&ping__ping_req__descriptor,
                                allocator, len, data);
}
void   ping__ping_req__free_unpacked
                     (Ping__PingReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ping__ping_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ping__ping_rsp__init
                     (Ping__PingRsp         *message)
{
  static const Ping__PingRsp init_value = PING__PING_RSP__INIT;
  *message = init_value;
}
size_t ping__ping_rsp__get_packed_size
                     (const Ping__PingRsp *message)
{
  assert(message->base.descriptor == &ping__ping_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ping__ping_rsp__pack
                     (const Ping__PingRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ping__ping_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ping__ping_rsp__pack_to_buffer
                     (const Ping__PingRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ping__ping_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ping__PingRsp *
       ping__ping_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ping__PingRsp *)
     protobuf_c_message_unpack (&ping__ping_rsp__descriptor,
                                allocator, len, data);
}
void   ping__ping_rsp__free_unpacked
                     (Ping__PingRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ping__ping_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ping__ping_req__field_descriptors[1] =
{
  {
    "sno",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ping__PingReq, sno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ping__ping_req__field_indices_by_name[] = {
  0,   /* field[0] = sno */
};
static const ProtobufCIntRange ping__ping_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ping__ping_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ping.ping_req",
  "PingReq",
  "Ping__PingReq",
  "ping",
  sizeof(Ping__PingReq),
  1,
  ping__ping_req__field_descriptors,
  ping__ping_req__field_indices_by_name,
  1,  ping__ping_req__number_ranges,
  (ProtobufCMessageInit) ping__ping_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ping__ping_rsp__field_descriptors[1] =
{
  {
    "sno",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ping__PingRsp, sno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ping__ping_rsp__field_indices_by_name[] = {
  0,   /* field[0] = sno */
};
static const ProtobufCIntRange ping__ping_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ping__ping_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ping.ping_rsp",
  "PingRsp",
  "Ping__PingRsp",
  "ping",
  sizeof(Ping__PingRsp),
  1,
  ping__ping_rsp__field_descriptors,
  ping__ping_rsp__field_indices_by_name,
  1,  ping__ping_rsp__number_ranges,
  (ProtobufCMessageInit) ping__ping_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
